### ISSUE TITLE
Рассмотреть аналоги

### ISSUE THREAD

**Issue by Graddery** [Graddery/Amaretto#1]
Сделать список со ссылками на аналоги

**Comment by Graddery** [comment]
1. https://www.redbubble.com

**Comment by dradedam** [comment]
1. https://kupimerch.ru/?ysclid=loyqqru5fc344005040            -  "КупиМерч"
2. https://www.wildberries.ru/                                                   -  "Wildberries"
3. https://www.vsemayki.ru/?ysclid=loyqr9l9is523680661        -  "Vsemayki"
